---
name: CI pipeline

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: [1.10.3]
        erlang: [22.3.3]
        os: [debian-buster-20200224]
    container:
      image: hexpm/elixir:${{ matrix.elixir }}-erlang-${{ matrix.erlang }}-${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Cache deps
        uses: actions/cache@v1
        with:
          path: deps
          key: deps-${{ hashFiles('mix.lock') }}
          restore-keys: |
            deps-
      - name: Install dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Compile project
        run: mix compile --warnings-as-errors
      - name: Cache priv/plts
        uses: actions/cache@v1
        with:
          path: priv/plts
          key: plts-${{ matrix.erlang }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            plts-${{ matrix.erlang }}-${{ matrix.elixir }}-
      - name: Run dialyzer
        run: mix dialyzer --format short
      - name: Run Credo
        run: mix credo -a
      - name: Check code formatting
        run: mix format --check-formatted

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: [1.10.3]
        erlang: [22.3.3]
        os: [debian-buster-20200224]
    container:
      image: hexpm/elixir:${{ matrix.elixir }}-erlang-${{ matrix.erlang }}-${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          mix local.hex --force
          mix test
