---
name: CI pipeline

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: hexpm/elixir:1.10.2-erlang-22.3.2-debian-buster-20200224
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
      - run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Analyze code
        run: |
          mix compile --warnings-as-errors
          mix credo -a
          mix format --check-formatted
      - name: Run tests
        run: mix test
