---
name: CI pipeline

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - master
  push:
    branches:
      - master

jobs:
  deps:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: [1.10.3]
        erlang: [22.3.4]
        os: [debian-buster-20200224]
    container:
      image: hexpm/elixir-amd64:${{ matrix.elixir }}-erlang-${{ matrix.erlang }}-${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            $HOME/.mix
            deps
          key: mix-${{ matrix.elixir }}-deps-${{ hashFiles('mix.lock') }}
          restore-keys: |
            mix-${{ matrix.elixir }}-deps-
            mix-
      - name: Install hex, rebar and get deps
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          rm -rf $HOME/.mix/*
          mix local.hex --force
          mix local.rebar --force
          mix deps.get
  build:
    needs: deps
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: [1.10.3]
        erlang: [22.3.4]
        os: [debian-buster-20200224]
    container:
      image: hexpm/elixir-amd64:${{ matrix.elixir }}-erlang-${{ matrix.erlang }}-${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Restore mix and deps from cache
        uses: actions/cache@v2
        with:
          path: |
            $HOME/.mix
            deps
          key: mix-${{ matrix.elixir }}-deps-${{ hashFiles('mix.lock') }}
      - name: Compile project
        run: mix compile --warnings-as-errors
      - uses: actions/cache@v2
        with:
          path: priv/plts
          key: plts-${{ matrix.erlang }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            plts-${{ matrix.erlang }}-${{ matrix.elixir }}-
      - name: Run dialyzer
        run: mix dialyzer --format short
      - name: Run Credo
        run: mix credo -a
      - name: Check code formatting
        run: mix format --check-formatted
  test:
    needs: deps
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: [1.10.3]
        erlang: [22.3.4]
        os: [debian-buster-20200224]
    container:
      image: hexpm/elixir-amd64:${{ matrix.elixir }}-erlang-${{ matrix.erlang }}-${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Restore mix and deps from cache
        uses: actions/cache@v2
        with:
          path: |
            $HOME/.mix
            deps
          key: mix-${{ matrix.elixir }}-deps-${{ hashFiles('mix.lock') }}
      - name: Run tests
        run: mix test
